language: python
python:
- '3.5'
- '3.6'
- '3.7'
notifications:
  email: false
env:
  matrix:
  - NUMPY="<1.15"
  - NUMPY="<1.16"
  - NUMPY="<1.17"
  - NUMPY="<1.18"
  - NUMPY=">=1.18"
install:
# numpy (must be installed before pyfftw, unwrap)
- travis_retry pip install "numpy${NUMPY}"
# everything else
- "travis_retry pip install . --only-binary=:all:"
- travis_retry pip install coverage coveralls
# coverage packages
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- pip freeze
script:
- coverage run --source=radontea setup.py test
- coverage report -m
- codecov
- flake8 radontea
- flake8 examples
- flake8 tests
deploy:
  provider: pypi
  user: "ci_qpi"
  password:
    secure: "gGXLQTjTVeO0cDDQ1CMdYdaTIiA1AXZkPnby7BLObsHZqtgJRH9S0o33LtLNtCC9XGYjdvaAk2m7BYn9JhKNCe3W48WwrE7KzX8T2ZO+Rfv5Eg7471b9Ncw1umgg6Ip+baw7tDN5Mik6zNGlncHDalnJPMgMvb1xyJMhegbBlT8="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  skip_existing: true

