language: python
python:
- '3.4'
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - NUMPY="1.11"
  - NUMPY="1.12"
  - NUMPY="1.13"
  - NUMPY="1.14"
install:
# numpy (must be installed before pyfftw, unwrap)
- travis_retry pip install "numpy==$NUMPY"
# everything else
- "travis_retry pip install . --only-binary=:all:"
- travis_retry pip install coverage coveralls
# coverage packages
- pip freeze
script:
- coverage run --source=radontea ./setup.py test
- coverage report -m
after_success:
- coveralls --verbose
