language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 'nightly'
notifications:
  email: false
env:
  matrix:
  - NUMPY="1.10.1"
  - NUMPY="1.11.3"
  - NUMPY="1.12.1"
  - NUMPY="1.13.1"
install:
# numpy (must be installed before pyfftw, unwrap)
- travis_retry pip install "numpy==$NUMPY"
# everything else
- "travis_retry pip install . --only-binary=:all:"
- travis_retry pip install coverage coveralls
# coverage packages
- pip freeze
script:
- coverage run --source=radontea ./setup.py test
- coverage report -m
after_success:
- coveralls --verbose
