language: python
python:
- '3.4'
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - NUMPY="1.11"
  - NUMPY="1.12"
  - NUMPY="1.13"
  - NUMPY="1.14"
install:
# numpy (must be installed before pyfftw, unwrap)
- travis_retry pip install "numpy==$NUMPY"
# everything else
- "travis_retry pip install . --only-binary=:all:"
- travis_retry pip install coverage coveralls
# coverage packages
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- pip freeze
script:
- set -ev
- if [ "${TEST}" == "PYTEST" ]; then
       coverage run --source=radontea setup.py test;
       coverage report -m;
       codecov;
  else
       flake8 radontea;
       flake8 examples;
       flake8 tests;
  fi;
