language: python
python:
- "2.7"
- "3.4"
branches:
  only:
  - master
before_install:
# We need to use conda, because virtualenv did not work on travis with 3.4
- sudo apt-get update -qq
- travis_retry sudo apt-get -y install python-numpy
- travis_retry sudo apt-get -y install python-scipy
- travis_retry pip install coveralls
install:
- travis_retry python setup.py develop
script:
  - coverage run --source=multipletau tests/runtests.py
  - coverage report -m
after_success:
  coveralls --verbose
